### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NQNStudios** [darmie/hxComposer#1]
Hi there! I'm working on a text-adventure scripting language in Haxe, and someone pointed this module out to me. It might be helpful for some things I hope to accomplish in my language: https://github.com/NQNStudios/hank/issues/43

Would you consider adding an open-source license file to the repository so it will be legal to use and modify/contribute back to?

**Comment by darmie** [comment]
Hi @NQNStudios , this project was an experiment and I didn't even get to use it. I am glad someone finds it useful. 

I will add an MIT license.

**Comment by darmie** [comment]
Done 👍
